import { resolve } from "path";

import { defineConfig } from "vite";

import { assetpackPlugin } from "./scripts/assetpack-vite-plugin";

// https://vite.dev/config/
export default defineConfig({
  plugins: [assetpackPlugin()],
  server: {
    port: 8080,
    open: "/main-web-cam-border.html",
  },
  build: {
    rollupOptions: {
      input: {
        mainWebCamBorder: resolve(__dirname, "main-web-cam-border.html"),
        planetCircleWebcamBorder: resolve(
          __dirname,
          "planet-circle-webcam-border.html",
        ),
        titlePowerline: resolve(__dirname, "title-powerline.html"),
        logo: resolve(__dirname, "logo.html"),
        proceduralLogo: resolve(__dirname, "procedural-logo.html"),
        background: resolve(__dirname, "background.html"),
        startingSoon: resolve(__dirname, "starting-soon.html"),
        musicBreak: resolve(__dirname, "music-break.html"),
        break: resolve(__dirname, "break.html"),
        planet: resolve(__dirname, "planet.html"),
        aquarium: resolve(__dirname, "aquarium.html"),
        atom: resolve(__dirname, "atom.html"),
        simpleWebCamBorder: resolve(__dirname, "simple-web-cam-border.html"),
        matrixDots: resolve(__dirname, "matrix-dots.html"),
        waveCam: resolve(__dirname, "wavecam.html"),
        trapCam: resolve(__dirname, "trapcam.html"),
        generative: resolve(__dirname, "generative.html"),
        hexCam: resolve(__dirname, "hexcam.html"),
        hexGridCam: resolve(__dirname, "hexgridcam.html"),
        hexLayerCam: resolve(__dirname, "hexlayercam.html"),
        triangulation: resolve(__dirname, "triangulation.html"),
        rain: resolve(__dirname, "rain.html"),
        flightSimulation: resolve(__dirname, "flight-simulation.html"),
        grass: resolve(__dirname, "grass.html"),
        graphBg: resolve(__dirname, "graph-bg.html"),
        starField: resolve(__dirname, "star-field.html"),
        maurerRose: resolve(__dirname, "maurer-rose.html"),
        collatz: resolve(__dirname, "collatz.html"),
        perlinBlobs: resolve(__dirname, "perlin-blobs.html"),
        planetHologram: resolve(__dirname, "planet-hologram.html"),
        particleSplash: resolve(__dirname, "particle-splash.html"),
        plexusConstellation: resolve(__dirname, "plexus-constellation.html"),
        flowField: resolve(__dirname, "flow-field.html"),
        gravitySphere: resolve(__dirname, "gravity-sphere.html"),
        lissajous: resolve(__dirname, "lissajous.html"),
        tunnelVortex: resolve(__dirname, "tunnel-vortex.html"),
        spiralPull: resolve(__dirname, "spiral-pull.html"),
        plasmaWave: resolve(__dirname, "plasma-wave.html"),
        magneticField: resolve(__dirname, "magnetic-field.html"),
        life: resolve(__dirname, "life.html"),
        particleGlobe: resolve(__dirname, "particle-globe.html"),
        auroraBorealis: resolve(__dirname, "aurora-borealis.html"),
        fourierEpicycles: resolve(__dirname, "fourier-epicycles.html"),
        hexRipple: resolve(__dirname, "hex-ripple.html"),
        stippledGeodesic: resolve(__dirname, "stippled-geodesic.html"),
        geodesicSphere: resolve(__dirname, "geodesic-sphere.html"),
        wireframeIcosphere: resolve(__dirname, "wireframe-icosphere.html"),
        nebula: resolve(__dirname, "nebula.html"),
        blackHoleCam: resolve(__dirname, "black-hole-cam.html"),
        accretionDiskCam: resolve(__dirname, "accretion-disk-cam.html"),
        nbody: resolve(__dirname, "nbody.html"),
        orbitalMechanics: resolve(__dirname, "orbital-mechanics.html"),
        solarWind: resolve(__dirname, "solar-wind.html"),
        shockWave: resolve(__dirname, "shock-wave.html"),
        boids: resolve(__dirname, "boids.html"),
        linuxBoids: resolve(__dirname, "linux-boids.html"),
        linuxIconMesh: resolve(__dirname, "linux-icon-mesh.html"),
        catppuccinLinuxOverlay: resolve(
          __dirname,
          "catppuccin-linux-overlay.html",
        ),
        emberPentagramOverlay: resolve(
          __dirname,
          "ember-pentagram-overlay.html",
        ),
        verletCloth: resolve(__dirname, "verlet-cloth.html"),
        sph: resolve(__dirname, "sph.html"),
        wireframeSphereCam: resolve(__dirname, "wireframe-sphere-cam.html"),
        cosmicPortal: resolve(__dirname, "cosmic-portal.html"),
        camFrameOverlay: resolve(__dirname, "cam-frame-overlay.html"),
        smokeRingCam: resolve(__dirname, "smoke-ring-cam.html"),
        elasticRings: resolve(__dirname, "elastic-rings.html"),
        galaxyBg: resolve(__dirname, "galaxy-bg.html"),
        pcbBg: resolve(__dirname, "pcb-bg.html"),
        infinity: resolve(__dirname, "infinity.html"),
        topoLandscape: resolve(__dirname, "topo-landscape.html"),
        cubicBlobOverlay: resolve(__dirname, "cubic-blob-overlay.html"),
        cubicBlobFaceOverlay: resolve(
          __dirname,
          "cubic-blob-face-overlay.html",
        ),
        confidential: resolve(__dirname, "confidential.html"),
        trapnation: resolve(__dirname, "trapnation.html"),
        index: resolve(__dirname, "index.html"),
        smokeBar: resolve(__dirname, "smoke-bar.html"),
        voronoiStippling: resolve(__dirname, "voronoi-stippling.html"),
        crystalcam: resolve(__dirname, "crystalcam.html"),
        figureEightTorus: resolve(__dirname, "figure-eight-torus.html"),
        wavyCam: resolve(__dirname, "wavy-cam.html"),
        fluidCircleCam: resolve(__dirname, "fluid-circle-cam.html"),
        fluidCatppuccinRingsCam: resolve(
          __dirname,
          "fluid-catppuccin-rings-cam.html",
        ),
        fluidDottedRingCam: resolve(__dirname, "fluid-dotted-ring-cam.html"),
        fluidMeshRingCam: resolve(__dirname, "fluid-mesh-ring-cam.html"),
        gasCam: resolve(__dirname, "gas-cam.html"),
        screenCaptureBorder: resolve(__dirname, "screen-capture-border.html"),
        worxbendText: resolve(__dirname, "worxbend-text.html"),
        worxbendFluid: resolve(__dirname, "worxbend-fluid.html"),
        worxbendMolecular: resolve(__dirname, "worxbend-molecular.html"),
        worxbend3dText: resolve(__dirname, "worxbend-3d-text.html"),
        startingSoonJelly: resolve(__dirname, "starting-soon-jelly.html"),
        startingSoonFluid: resolve(__dirname, "starting-soon-fluid.html"),
        startingSoonParticleMesh: resolve(
          __dirname,
          "starting-soon-particle-mesh.html",
        ),
        streamEndedParticleMesh: resolve(
          __dirname,
          "stream-ended-particle-mesh.html",
        ),
        topography: resolve(__dirname, "topography.html"),
        dottedMesh: resolve(__dirname, "dotted-mesh.html"),
        wavyPlanetMesh: resolve(__dirname, "wavy-planet-mesh.html"),
        catMesh: resolve(__dirname, "cat-mesh.html"),
        nightCityHorizon: resolve(__dirname, "night-city-horizon.html"),
        microbialColony: resolve(__dirname, "microbial-colony.html"),
        avatar: resolve(__dirname, "avatar.html"),
        fluidPaint: resolve(__dirname, "fluid-paint.html"),
        waveBorderCam: resolve(__dirname, "wave-border-cam.html"),
        catCircleCam: resolve(__dirname, "cat-circle-cam.html"),
        threeRingCamBorder: resolve(__dirname, "three-ring-cam-border.html"),
        threeGeoCamBorder: resolve(__dirname, "three-geo-cam-border.html"),
        jellyRingCamBorder: resolve(__dirname, "jelly-ring-cam-border.html"),
        animatedLines: resolve(__dirname, "animated-lines.html"),
        mountainNightRailway: resolve(__dirname, "mountain-night-railway.html"),
        tuxBlob: resolve(__dirname, "tux-blob.html"),
        bioluminescentCell: resolve(__dirname, "bioluminescent-cell.html"),
        metaBlobs: resolve(__dirname, "meta-blobs.html"),
        iridescentBlobs: resolve(__dirname, "iridescent-blobs.html"),
        physicsParticles: resolve(__dirname, "physics-particles.html"),
        spaceWarBoids: resolve(__dirname, "space-war-boids.html"),
        amorphousSquareBorder: resolve(
          __dirname,
          "amorphous-square-border.html",
        ),
        darkSunCam: resolve(__dirname, "dark-sun-cam.html"),
        lavenderDashesCam: resolve(__dirname, "lavender-dashes-cam.html"),
        amorphousBlobCam: resolve(__dirname, "amorphous-blob-cam.html"),
        ukrainianWaveMesh: resolve(__dirname, "ukrainian-wave-mesh.html"),
        uaRedBlackMesh: resolve(__dirname, "ua-red-black-mesh.html"),
        hypeMeterCam: resolve(__dirname, "hype-meter-cam.html"),
        mainAudioActivatedBorder: resolve(
          __dirname,
          "main-audio-activated-border.html",
        ),
        blobFaceCam: resolve(__dirname, "blob-face-cam.html"),
        vectorFieldBg: resolve(__dirname, "vector-field-bg.html"),
        wormholeDive: resolve(__dirname, "wormhole-dive.html"),
        gaussianDistributionBg: resolve(
          __dirname,
          "gaussian-distribution-bg.html",
        ),
        myceliumNetwork: resolve(__dirname, "mycelium-network.html"),
        particleConstellation: resolve(
          __dirname,
          "particle-constellation.html",
        ),
        radialEnergyCore: resolve(__dirname, "radial-energy-core.html"),
        liquidAuroraField: resolve(__dirname, "liquid-aurora-field.html"),
        inkInWater: resolve(__dirname, "ink-in-water.html"),
        minimalistGradientBreathing: resolve(
          __dirname,
          "minimalist-gradient-breathing.html",
        ),
        breakWaterText: resolve(__dirname, "break-water-text.html"),
        forestAmbientBg: resolve(__dirname, "forest-ambient-bg.html"),
        chaosAttractor: resolve(__dirname, "chaos-attractor.html"),
        chaoticParticles: resolve(__dirname, "chaotic-particles.html"),
        fireball: resolve(__dirname, "fireball.html"),
        greenFireball: resolve(__dirname, "green-fireball.html"),
        handwrittenNotebook: resolve(__dirname, "handwritten-notebook.html"),
        fpvBlueprintBg: resolve(__dirname, "fpv-blueprint-bg.html"),
        blueprintGlobe: resolve(__dirname, "blueprint-globe.html"),
        linuxBlueprint: resolve(__dirname, "linux-blueprint.html"),
        voidImplode: resolve(__dirname, "void-implode.html"),
        networkSurge: resolve(__dirname, "network-surge.html"),
        ambientEnergy: resolve(__dirname, "ambient-energy.html"),
        waveSimulation: resolve(__dirname, "wave-simulation.html"),
        gpuBoids: resolve(__dirname, "gpu-boids.html"),
        waveInterference: resolve(__dirname, "wave-interference.html"),
        softBodyOrganisms: resolve(__dirname, "soft-body-organisms.html"),
        audioFlowTurbulence: resolve(__dirname, "audio-flow-turbulence.html"),
        particleSwarmExcitement: resolve(
          __dirname,
          "particle-swarm-excitement.html",
        ),
        audioNeuralNet: resolve(__dirname, "audio-neural-net.html"),
        neuralDatacenter: resolve(__dirname, "neural-datacenter.html"),
        sciFiHud: resolve(__dirname, "sci-fi-hud.html"),
        geometricLines: resolve(__dirname, "geometric-lines.html"),
        cellularSlime: resolve(__dirname, "cellular-slime.html"),
        artificialLife: resolve(__dirname, "artificial-life.html"),
        softBodyCube: resolve(__dirname, "soft-body-cube.html"),
        jellyBlobFace: resolve(__dirname, "jelly-blob-face.html"),
        physarumGol: resolve(__dirname, "physarum-gol.html"),
        crystalGrowth: resolve(__dirname, "crystal-growth.html"),
        japaneseTempleLofi: resolve(__dirname, "japanese-temple-lofi.html"),
        dataCorruption: resolve(__dirname, "data-corruption.html"),
        aiInference: resolve(__dirname, "ai-inference.html"),
        glitchOverlay: resolve(__dirname, "glitch-overlay.html"),
        retroScreenFilter: resolve(__dirname, "retro-screen-filter.html"),
        rainOnGlass: resolve(__dirname, "rain-on-glass.html"),
        distributedSystems: resolve(__dirname, "distributed-systems.html"),
        gitActivity: resolve(__dirname, "git-activity.html"),
        codeOcean: resolve(__dirname, "code-ocean.html"),
        cityView: resolve(__dirname, "city-view.html"),
        cyclopsAvatar: resolve(__dirname, "cyclops-avatar.html"),
        particleBorderOverlay: resolve(
          __dirname,
          "particle-border-overlay.html",
        ),
        softVolFog: resolve(__dirname, "soft-vol-fog.html"),
        monolithicBlackGeometry: resolve(
          __dirname,
          "monolithic-black-geometry.html",
        ),
        slimeMoldNetwork: resolve(__dirname, "slime-mold-network.html"),
        reactiveEnergyMembrane: resolve(
          __dirname,
          "reactive-energy-membrane.html",
        ),
        digitalFluidInk: resolve(__dirname, "digital-fluid-ink.html"),
        solarSystem: resolve(__dirname, "solar-system.html"),
        fireOrb: resolve(__dirname, "fire-orb.html"),
        jellyBlobs: resolve(__dirname, "jelly-blobs.html"),
        discordRobot: resolve(__dirname, "discord-robot.html"),
        octocatRobot: resolve(__dirname, "octocat-robot.html"),
        gunanSkeleton: resolve(__dirname, "gunan-skeleton.html"),
        zombieFbx: resolve(__dirname, "zombie-fbx.html"),
        meshyAvatar: resolve(__dirname, "meshy-avatar.html"),
        droneVisualization: resolve(__dirname, "drone-visualization.html"),
        ergodoxShowroom: resolve(__dirname, "ergodox-showroom.html"),
        djiFpv: resolve(__dirname, "dji-fpv.html"),
        hexWaterIsland: resolve(__dirname, "hex-water-island.html"),
      },
    },
  },
  define: {
    APP_VERSION: JSON.stringify(process.env.npm_package_version),
  },
});
