import {
  CATT_BLUE,
  CATT_FLAMINGO,
  CATT_GREEN,
  CATT_LAVENDER,
  CATT_MAUVE,
  CATT_OVERLAY0,
  CATT_PEACH,
  CATT_RED,
  CATT_ROSEWATER,
  CATT_SKY,
  CATT_SURFACE0,
  CATT_TEAL,
  CATT_YELLOW,
} from "./constants";
import type { PlanetDef } from "./types";

// ── Planet definitions ────────────────────────────────────────────────────────
// Orbits spread 0.17–1.0, with generous gaps between each planet
export const PLANET_DEFS: PlanetDef[] = [
  // Mercury — pushed further out from sun
  {
    semiMajorFrac: 0.17,
    eccentricity: 0.21,
    inclination: 0.0,
    period: 9,
    size: 5,
    color: CATT_ROSEWATER,
    atmoColor: CATT_FLAMINGO,
    hasRings: false,
    ringColor: 0,
    trailLen: 22,
    moons: [],
  },
  // Venus
  {
    semiMajorFrac: 0.25,
    eccentricity: 0.007,
    inclination: 0.35,
    period: 16,
    size: 8,
    color: CATT_PEACH,
    atmoColor: CATT_YELLOW,
    hasRings: false,
    ringColor: 0,
    trailLen: 28,
    moons: [],
  },
  // Earth
  {
    semiMajorFrac: 0.34,
    eccentricity: 0.017,
    inclination: -0.18,
    period: 24,
    size: 9,
    color: CATT_GREEN,
    atmoColor: CATT_BLUE,
    hasRings: false,
    ringColor: 0,
    trailLen: 32,
    moons: [{ orbitFrac: 0.09, period: 2.7, size: 2.5, color: CATT_OVERLAY0 }],
  },
  // Mars
  {
    semiMajorFrac: 0.44,
    eccentricity: 0.093,
    inclination: 0.52,
    period: 34,
    size: 7,
    color: CATT_RED,
    atmoColor: CATT_FLAMINGO,
    hasRings: false,
    ringColor: 0,
    trailLen: 34,
    moons: [
      { orbitFrac: 0.07, period: 1.3, size: 1.5, color: CATT_OVERLAY0 },
      { orbitFrac: 0.13, period: 2.5, size: 1.5, color: CATT_SURFACE0 },
    ],
  },
  // Jupiter
  {
    semiMajorFrac: 0.6,
    eccentricity: 0.049,
    inclination: -0.08,
    period: 68,
    size: 20,
    color: CATT_PEACH,
    atmoColor: CATT_YELLOW,
    hasRings: false,
    ringColor: 0,
    trailLen: 42,
    moons: [
      { orbitFrac: 0.05, period: 1.8, size: 3.0, color: CATT_FLAMINGO },
      { orbitFrac: 0.08, period: 2.9, size: 2.5, color: CATT_ROSEWATER },
      { orbitFrac: 0.12, period: 4.6, size: 3.5, color: CATT_OVERLAY0 },
      { orbitFrac: 0.17, period: 8.0, size: 2.0, color: CATT_SURFACE0 },
    ],
  },
  // Saturn
  {
    semiMajorFrac: 0.72,
    eccentricity: 0.057,
    inclination: 0.72,
    period: 92,
    size: 17,
    color: CATT_YELLOW,
    atmoColor: CATT_PEACH,
    hasRings: true,
    ringColor: CATT_YELLOW,
    trailLen: 46,
    moons: [
      { orbitFrac: 0.06, period: 2.2, size: 2.5, color: CATT_ROSEWATER },
      { orbitFrac: 0.11, period: 3.8, size: 3.0, color: CATT_OVERLAY0 },
    ],
  },
  // Uranus
  {
    semiMajorFrac: 0.83,
    eccentricity: 0.044,
    inclination: -0.55,
    period: 118,
    size: 13,
    color: CATT_SKY,
    atmoColor: CATT_TEAL,
    hasRings: true,
    ringColor: CATT_TEAL,
    trailLen: 50,
    moons: [
      { orbitFrac: 0.07, period: 3.0, size: 2.0, color: CATT_LAVENDER },
      { orbitFrac: 0.12, period: 5.2, size: 2.0, color: CATT_BLUE },
    ],
  },
  // Neptune
  {
    semiMajorFrac: 0.95,
    eccentricity: 0.01,
    inclination: 1.1,
    period: 144,
    size: 12,
    color: CATT_BLUE,
    atmoColor: CATT_MAUVE,
    hasRings: false,
    ringColor: 0,
    trailLen: 54,
    moons: [{ orbitFrac: 0.06, period: 2.8, size: 2.0, color: CATT_LAVENDER }],
  },
  // Rogue dwarf — highly eccentric, crosses multiple orbits
  {
    semiMajorFrac: 0.68,
    eccentricity: 0.78,
    inclination: 2.1,
    period: 100,
    size: 4,
    color: CATT_MAUVE,
    atmoColor: CATT_LAVENDER,
    hasRings: false,
    ringColor: 0,
    trailLen: 60,
    moons: [],
  },
];
